listener 1883
allow_anonymous false

listener 9001
protocol websockets
allow_anonymous false

password_file /mosquitto/data/password_file
acl_file /mosquitto/config/mosquitto.acl

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
